#!/usr/bin/env bash
# Solve and verify the four recovered Eternity II clue puzzles, then regenerate
# the web data modules (piece sets for download + solved boards for rendering).
# Deterministic given the same kissat build. Requires kissat and python3.
set -euo pipefail
cd "$(dirname "$0")"

BIN=compute/target/release/cluesolve
[ -x "$BIN" ] || (cd compute && cargo build --release >/dev/null 2>&1)

WEB=../../../web/src/data

solve() { # <file> <w> <h> <name>
  "$BIN" "data/$1" "$2" "$3" > "results/$4-solution.json"
  echo "$4: $(grep -o '"validated": [a-z]*' "results/$4-solution.json"), $(grep -o '"matchedInternalEdges": [0-9]*' "results/$4-solution.json")"
}

solve clue1_shorter36.txt 6 6 clue1
solve clue2_shorter72.txt 12 6 clue2
solve clue3_jwortmann.txt 6 6 clue3
solve clue4_jwortmann.txt 12 6 clue4

# Emit web/src/data/clue-puzzle-solutions.ts from the validated JSON results.
python3 - "$WEB" <<'PY'
import json, sys
web = sys.argv[1]
meta = {"clue1": ("clue1", 6, 6), "clue2": ("clue2", 12, 6),
        "clue3": ("clue3", 6, 6), "clue4": ("clue4", 12, 6)}
L = [
 "// Solved clue-puzzle boards, generated by research/topics/clue-puzzle-pieces.",
 "// Each cell is [up, right, down, left] edge colours (URDL); 0 = grey border.",
 "// Colours are compacted to 1..k and rendered with the real Eternity II motif",
 "// set (see clue-puzzles.mdx colour note). Do not hand-edit; regenerate via run.sh.",
 'import type { Edges } from "@/lib/bucas";',
 "",
 "export interface ClueSolution { w: number; h: number; cells: Edges[]; }",
 "",
]
for k, (name, w, h) in meta.items():
    d = json.load(open(f"results/{name}-solution.json"))
    assert d["validated"] and d["matchedInternalEdges"] == d["internalEdges"], name
    cells = ", ".join("[" + ",".join(str(e) for e in c) + "]" for c in d["solutionURDL"])
    L.append(f"export const {k.upper()}_SOLVED: ClueSolution = {{ w: {w}, h: {h}, cells: [{cells}] }};")
open(f"{web}/clue-puzzle-solutions.ts", "w").write("\n".join(L) + "\n")
print("wrote clue-puzzle-solutions.ts")
PY

echo "done"
