import { pageMeta } from "@/seo";
// Algorithms, explained for high-schoolers, with real measurements from the
// site's own Rust engine (src/data/difficulty.json is generated by
// `cargo run --release --bin stats` in engine/).

import { LocalizedLink as Link } from "@/components/LocalizedLink";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Legend,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { DfsDemo } from "@/components/learn/DfsDemo";
import { TimeToSolve } from "@/components/learn/TimeToSolve";
import { PathDiagrams } from "@/components/learn/PathDiagrams";
import { BinaryPlayground } from "@/components/learn/BinaryPlayground";
import { useT } from "@/i18n";
import stats from "@/data/difficulty.json";
import { formatCompact } from "@/lib/format";

interface DifficultyRow {
  size: number;
  colors: number;
  median: number;
  min: number;
  max: number;
  censored: number;
  seeds: number;
}

interface PathRow {
  kind: string;
  median: number;
  censored: number;
}

interface SpaceRow {
  size: number;
  log10Naive: number;
  log10Refined: number;
}

const difficulty = stats.difficulty as DifficultyRow[];
const pathRows = [...(stats.paths as PathRow[])].sort((a, b) => a.median - b.median);
const spaceRows = stats.searchSpace as SpaceRow[];

// One line per board size: median work vs number of colors. 3×3 is omitted —
// it solves near-instantly and just hugs the bottom axis without adding signal.
const SIZES = [...new Set(difficulty.map((d) => d.size))].filter((s) => s !== 3);
const colorsDomain = [...new Set(difficulty.map((d) => d.colors))].sort((a, b) => a - b);
const difficultyChart = colorsDomain.map((colors) => {
  const row: Record<string, number | null> = { colors };
  for (const s of SIZES) {
    const hit = difficulty.find((d) => d.size === s && d.colors === colors);
    row[`s${s}`] = hit ? hit.median : null;
  }
  return row;
});

const SIZE_COLORS: Record<number, string> = {
  3: "#94a3b8",
  4: "#38bdf8",
  5: "#34d399",
  6: "#fbbf24",
  7: "#fb923c",
  8: "#f87171",
};

const T = {
  en: {
    title: "How do you teach a computer to solve puzzles?",
    intro: (
      <>
        No magic here, just three big ideas: <strong>trying things in order</strong>,{" "}
        <strong>undoing mistakes</strong>, and <strong>counting how bad it can get</strong>.
        Every number and chart on this page was measured by the same Rust engine that powers
        the <Link className="underline" to="/playground">playground</Link>, running on puzzles
        it generated itself.
      </>
    ),
    s1Title: "1 · Depth-first search: the maze strategy",
    s1P1: (
      <>
        Imagine exploring a maze: at every junction take the first corridor you haven't tried;
        when you hit a dead end, walk back to the last junction and take the next corridor.
        That's <strong>depth-first search (DFS)</strong>, and it's exactly how our solver
        plays Eternity II. The "junction" is an empty square; the "corridors" are every piece
        × rotation that still fits; the "walk back" is called <strong>backtracking</strong>.
      </>
    ),
    s1P2: (
      <>
        DFS is <em>complete</em>: given enough time it tries everything, so if a solution
        exists, it will be found. The catch is in the words "enough time". Here it is, slowed
        down to one decision per second:
      </>
    ),
    watchFullSpeed: "▶ Now watch it at full speed",
    s2Title: "2 · The exponential wall",
    s2P1: (
      <>
        How big is "everything"? For an n×n puzzle there are roughly n²! ways to order the
        pieces times 4 rotations each. The chart below shows the <em>number of digits</em> in
        that count. Notice it's a straight-ish line: every step up in size multiplies the work
        by an astronomical factor. The 16×16 box on your shelf sits at ≈560 digits.
      </>
    ),
    spaceChartTitle: "Digits in the search-space size, by board size",
    axisDigits: "digits",
    boardTooltip: (s: number | string) => `${s}×${s} board`,
    legendNaive: "all arrangements",
    legendRefined: "after corner/border deductions",
    s2P2: (
      <>
        The blue line is the first lesson in algorithm design: <strong>deductions shrink
        worlds</strong>. Just noticing that corner pieces must go in corners and border pieces
        on the rim removes ~100 digits. Real solvers stack many such deductions. And it's
        still not nearly enough.
      </>
    ),
    s2P3: <>"Digits" stay abstract, so let's make it personal:</>,
    zeroWallTitle: "How long is a 560-digit number? This long:",
    zeroWallCaption:
      "One followed by 559 zeros: 560 digits, exactly as many as the real count (about 9 × 10^559). Every single zero multiplies the count by ten.",
    s3Title: "3 · Measured difficulty: size and colors",
    s3Intro: (seeds: number | undefined) => (
      <>
        We generated hundreds of mini-puzzles and let the engine solve each one, counting{" "}
        <strong>nodes</strong> (candidate piece placements tested) until the first solution (median of {seeds}{" "}
        random puzzles per point; log scale!). Three things to see. Each extra row of board
        multiplies the work: the lines sit decades apart. <em>More</em> colors often make a
        puzzle <em>easier</em>, because wrong placements get rejected sooner instead of luring
        the search into deep dead ends. And every line shows something famous: a sharp{" "}
        <strong>hardness peak</strong>. Very few colors → tons of solutions, easy to stumble on
        one. Many colors → so constrained the search barely branches. The peak sits right in
        between — and, crucially, <strong>it slides to the right as the board grows</strong>: the
        6×6 line peaks at <strong>4 colors</strong>, the 8×8 line at <strong>6 colors</strong>,
        roughly one extra color per added row. At its peak the median 8×8 puzzle needs over{" "}
        <strong>2 billion</strong> piece placements, and most seeds there ran so long we had to
        stop measuring them (the flat tops are those censored points). One color either side and
        it collapses by a hundredfold. Extrapolate that one-color-per-row trend out to a 16×16
        board and the peak lands right around <strong>22 colors</strong> — exactly where
        Eternity II was built to sit. It isn't an accident past the peak; it's tuned to land
        <em> on</em> it.
      </>
    ),
    workChartTitle: "Work to solve (median nodes, log scale) vs number of colors",
    axisColors: "colors",
    fitChecks: "nodes",
    s4Title: "4 · The order you search in matters. A lot.",
    s4P1: (
      <>
        Same puzzles, same solver. The only change is the <em>order</em> in which squares get
        filled. Orders that keep new placements glued to already-placed neighbors (snake,
        spiral) constrain each step and prune early. Orders that scatter placements (random)
        leave pieces unconstrained and pay for it later. This is a real research topic, and
        you can <Link className="underline" to="/playground/paths">design your own order</Link>{" "}
        and race it. Here is what the classic orders actually look like; follow the arrows
        (red = first cell, green = last):
      </>
    ),
    pathChartTitle: "Median nodes on the same 6×6 puzzles, by fill order (log scale)",
    s5Title: "5 · Why computers think in binary here",
    s5P1: (
      <>
        A piece is just four small numbers (up, right, down, left motif). No pictures, no
        geometry. These four demos run live; watch them for a few seconds each:
      </>
    ),
    s5P2: (
      <>
        Stored as numbers, the entire official set is about 1&nbsp;KB. Serious solvers go
        further with <strong>bitsets</strong>: one 64-bit number carries a yes/no answer
        about 64 pieces at once, so a single CPU instruction filters 64 candidates
        simultaneously. That's how the fastest engines reach hundreds of millions of nodes
        per second. Representation, not just the algorithm, is part of the craft.
      </>
    ),
    s6Title: "6 · So how far does smart get you?",
    s6P1: (
      <>
        State-of-the-art attacks add constraint propagation (deduce forced placements before
        trying any), clever piece orderings, parallel search, and local-repair heuristics that
        fix imperfect boards. They reach 469 and 470 of 480 matched edges. Extraordinary, and
        still short. The gap between "almost solved" and "solved" is where the open research
        lives: see the <Link className="underline" to="/research">Research</Link> section.
      </>
    ),
  },
  fr: {
    title: "Comment apprendre à un ordinateur à résoudre des puzzles ?",
    intro: (
      <>
        Pas de magie ici, juste trois grandes idées : <strong>essayer les possibilités dans
        l'ordre</strong>, <strong>défaire ses erreurs</strong> et <strong>compter jusqu'où le
        travail peut grimper</strong>. Chaque nombre et chaque graphique de cette page a été
        mesuré par le moteur Rust qui fait tourner l'
        <Link className="underline" to="/playground">aire de jeu</Link>, sur des puzzles qu'il
        a générés lui-même.
      </>
    ),
    s1Title: "1 · Le parcours en profondeur : la stratégie du labyrinthe",
    s1P1: (
      <>
        Imaginez l'exploration d'un labyrinthe : à chaque croisement, prenez le premier
        couloir que vous n'avez pas encore essayé ; dans une impasse, revenez au dernier
        croisement et prenez le couloir suivant. C'est le <strong>parcours en profondeur
        (DFS)</strong>, et c'est exactement ainsi que notre solveur joue à Eternity II. Le
        « croisement », c'est une case vide ; les « couloirs », ce sont toutes les pièces et
        rotations qui conviennent encore ; le « demi-tour » s'appelle le <strong>retour en
        arrière</strong> (backtracking).
      </>
    ),
    s1P2: (
      <>
        Le DFS est <em>complet</em> : avec assez de temps, il essaie tout, donc si une
        solution existe, il finira par la trouver. Le piège se cache dans les mots « assez de
        temps ». Le voici, ralenti à une décision par seconde :
      </>
    ),
    watchFullSpeed: "▶ Regardez-le maintenant à pleine vitesse",
    s2Title: "2 · Le mur exponentiel",
    s2P1: (
      <>
        « Tout », c'est grand comment ? Pour un puzzle n×n, il existe environ n²! façons
        d'ordonner les pièces, fois 4 rotations chacune. Le graphique ci-dessous montre le{" "}
        <em>nombre de chiffres</em> de ce total. Remarquez que la ligne est presque droite :
        chaque taille supplémentaire multiplie le travail par un facteur astronomique. La
        boîte 16×16 posée sur votre étagère se situe vers 560 chiffres.
      </>
    ),
    spaceChartTitle: "Nombre de chiffres de l'espace de recherche, selon la taille du plateau",
    axisDigits: "chiffres",
    boardTooltip: (s: number | string) => `plateau ${s}×${s}`,
    legendNaive: "tous les arrangements",
    legendRefined: "après déductions coins/bords",
    s2P2: (
      <>
        La ligne bleue, c'est la première leçon de conception d'algorithmes : <strong>les
        déductions rétrécissent les mondes</strong>. Le simple fait de remarquer que les
        pièces de coin vont dans les coins et les pièces de bord sur le pourtour enlève
        environ 100 chiffres. Les vrais solveurs empilent beaucoup de déductions de ce genre.
        Et c'est encore très loin de suffire.
      </>
    ),
    s2P3: <>Des « chiffres », ça reste abstrait, alors voyons ce que ça donne sur votre machine :</>,
    zeroWallTitle: "À quoi ressemble un nombre de 560 chiffres ? À ceci :",
    zeroWallCaption:
      "Un suivi de 559 zéros : 560 chiffres, exactement autant que le vrai compte (environ 9 × 10^559). Chaque zéro multiplie le compte par dix.",
    s3Title: "3 · La difficulté mesurée : taille et couleurs",
    s3Intro: (seeds: number | undefined) => (
      <>
        Nous avons généré des centaines de mini-puzzles et laissé le moteur résoudre chacun
        d'eux, en comptant les <strong>nœuds</strong> (placements candidats testés) jusqu'à la première
        solution (médiane de {seeds} puzzles aléatoires par point ; échelle logarithmique !).
        Trois choses à observer. Chaque rangée de plateau en plus multiplie le travail : les
        lignes sont séparées de plusieurs ordres de grandeur. <em>Plus</em> de couleurs
        rendent souvent un puzzle <em>plus facile</em>, car les mauvais placements sont
        rejetés plus tôt au lieu d'entraîner la recherche dans des impasses profondes. Et
        chaque ligne montre un phénomène célèbre : un <strong>pic de difficulté</strong>. Très
        peu de couleurs → des tonnes de solutions, facile d'en trouver une par hasard. Beaucoup
        de couleurs → le puzzle est si contraint que la recherche se ramifie à peine. Le pic se
        situe juste entre les deux — et, surtout, <strong>il se décale vers la droite quand le
        plateau grandit</strong> : la ligne 6×6 culmine à <strong>4 couleurs</strong>, la ligne
        8×8 à <strong>6 couleurs</strong>, soit environ une couleur de plus par rangée ajoutée.
        À son pic, le puzzle 8×8 médian demande plus de <strong>2 milliards</strong> de
        placements de pièces, et la plupart des graines ont tourné si longtemps qu'il a fallu
        arrêter de les mesurer (les plateaux correspondent à ces points censurés). Une couleur
        de plus ou de moins, et tout s'effondre d'un facteur cent. Prolongez cette tendance
        d'une couleur par rangée jusqu'à un plateau 16×16, et le pic tombe pile autour de{" "}
        <strong>22 couleurs</strong> — exactement là où Eternity II a été conçu pour se situer.
        Ce n'est pas un hasard au-delà du pic ; il est calibré pour tomber <em>dessus</em>.
      </>
    ),
    workChartTitle:
      "Travail pour résoudre (médiane des nœuds, échelle log) selon le nombre de couleurs",
    axisColors: "couleurs",
    fitChecks: "nœuds",
    s4Title: "4 · L'ordre dans lequel on cherche compte. Énormément.",
    s4P1: (
      <>
        Mêmes puzzles, même solveur. Le seul changement, c'est l'<em>ordre</em> dans lequel
        les cases sont remplies. Les ordres qui gardent chaque nouveau placement collé à des
        voisins déjà posés (snake, spiral) contraignent chaque étape et élaguent tôt. Les
        ordres qui éparpillent les placements (random) laissent les pièces sans contrainte et
        le paient plus tard. C'est un vrai sujet de recherche, et vous pouvez{" "}
        <Link className="underline" to="/playground/paths">concevoir votre propre ordre</Link>{" "}
        et le faire courir contre les autres. Voici à quoi ressemblent vraiment les ordres
        classiques ; suivez les flèches (rouge = première case, vert = dernière) :
      </>
    ),
    pathChartTitle:
      "Médiane des nœuds sur les mêmes puzzles 6×6, selon l'ordre de remplissage (échelle log)",
    s5Title: "5 · Pourquoi les ordinateurs pensent ici en binaire",
    s5P1: (
      <>
        Une pièce, c'est juste quatre petits nombres (motifs haut, droite, bas, gauche). Pas
        d'images, pas de géométrie. Ces quatre démos tournent en direct ; observez chacune
        pendant quelques secondes :
      </>
    ),
    s5P2: (
      <>
        Rangé sous forme de nombres, le jeu officiel complet pèse environ 1&nbsp;Ko. Les
        solveurs sérieux vont plus loin avec les <strong>bitsets</strong> : un seul nombre de
        64 bits porte une réponse oui/non sur 64 pièces à la fois, donc une seule instruction
        du processeur filtre 64 candidates d'un coup. C'est ainsi que les moteurs les plus
        rapides atteignent des centaines de millions de nœuds par seconde. La représentation
        des données, pas seulement l'algorithme, fait partie du métier.
      </>
    ),
    s6Title: "6 · Alors, jusqu'où va-t-on en étant malin ?",
    s6P1: (
      <>
        Les attaques les plus avancées ajoutent la propagation de contraintes (déduire les
        placements forcés avant tout essai), des ordres de pièces astucieux, la recherche en
        parallèle et des heuristiques de réparation locale qui corrigent les plateaux
        imparfaits. Elles atteignent 469 et 470 côtés appariés sur 480. Extraordinaire, et
        pourtant pas assez. L'écart entre « presque résolu » et « résolu », c'est là que vit
        la recherche ouverte : voyez la section{" "}
        <Link className="underline" to="/research">Recherche</Link>.
      </>
    ),
  },
};

export default function Algorithms() {
  const t = useT(T);
  return (
    <div className="space-y-12">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">{t.title}</h1>
        <p className="mt-2 max-w-3xl text-muted-foreground">{t.intro}</p>
      </div>

      <section className="max-w-3xl space-y-3">
        <h2 className="text-2xl font-semibold tracking-tight">{t.s1Title}</h2>
        <p className="text-base leading-relaxed text-muted-foreground">{t.s1P1}</p>
        <p className="text-base leading-relaxed text-muted-foreground">{t.s1P2}</p>
        <DfsDemo />
        <Button variant="outline" size="sm" render={<Link to="/playground/watch" />}>
          {t.watchFullSpeed}
        </Button>
      </section>

      <section className="space-y-3">
        <h2 className="text-2xl font-semibold tracking-tight">{t.s2Title}</h2>
        <p className="max-w-3xl text-base leading-relaxed text-muted-foreground">{t.s2P1}</p>
        <Card>
          <CardHeader>
            <CardTitle className="text-base">{t.spaceChartTitle}</CardTitle>
          </CardHeader>
          <CardContent className="h-72">
            <ResponsiveContainer>
              <LineChart data={spaceRows} margin={{ top: 8, right: 24, bottom: 8, left: 8 }}>
                <CartesianGrid strokeDasharray="3 3" opacity={0.3} />
                <XAxis dataKey="size" tickFormatter={(s) => `${s}×${s}`} />
                <YAxis width={60} label={{ value: t.axisDigits, angle: -90, position: "insideLeft" }} />
                <Tooltip
                  formatter={(v) => [`10^${Number(v).toFixed(0)}`, ""]}
                  labelFormatter={(s) => t.boardTooltip(s)}
                />
                <Legend />
                <Line name={t.legendNaive} dataKey="log10Naive" stroke="#f87171" dot={false} strokeWidth={2} />
                <Line name={t.legendRefined} dataKey="log10Refined" stroke="#38bdf8" dot={false} strokeWidth={2} />
              </LineChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
        <p className="max-w-3xl text-base text-muted-foreground">{t.s2P2}</p>
        <div className="space-y-2">
          <p className="text-sm font-medium">{t.zeroWallTitle}</p>
          <div className="w-full rounded-lg border bg-muted/30 p-4 font-mono text-[11px] leading-relaxed break-all text-muted-foreground select-all">
            <span className="font-bold text-foreground">1</span>
            {"0".repeat(559)}
          </div>
          <p className="text-xs text-muted-foreground">{t.zeroWallCaption}</p>
        </div>
        <p className="max-w-3xl text-base text-muted-foreground">{t.s2P3}</p>
        <TimeToSolve />
      </section>

      <section className="space-y-3">
        <h2 className="text-2xl font-semibold tracking-tight">{t.s3Title}</h2>
        <p className="max-w-3xl text-base leading-relaxed text-muted-foreground">
          {t.s3Intro(difficulty[0]?.seeds)}
        </p>
        <Card>
          <CardHeader>
            <CardTitle className="text-base">{t.workChartTitle}</CardTitle>
          </CardHeader>
          <CardContent className="h-80">
            <ResponsiveContainer>
              <LineChart data={difficultyChart} margin={{ top: 8, right: 24, bottom: 8, left: 8 }}>
                <CartesianGrid strokeDasharray="3 3" opacity={0.3} />
                <XAxis dataKey="colors" label={{ value: t.axisColors, position: "insideBottom", offset: -2 }} />
                <YAxis
                  scale="log"
                  domain={[10, 3e9]}
                  ticks={[100, 1e4, 1e6, 1e8, 1e9]}
                  interval={0}
                  allowDataOverflow
                  width={70}
                  tickFormatter={(v) => formatCompact(Number(v))}
                />
                <Tooltip formatter={(v) => [formatCompact(Number(v)), t.fitChecks]} />
                <Legend />
                {SIZES.map((s) => (
                  <Line
                    key={s}
                    name={`${s}×${s}`}
                    dataKey={`s${s}`}
                    stroke={SIZE_COLORS[s] ?? "#a78bfa"}
                    dot={false}
                    strokeWidth={2}
                    connectNulls
                  />
                ))}
              </LineChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      </section>

      <section className="space-y-3">
        <h2 className="text-2xl font-semibold tracking-tight">{t.s4Title}</h2>
        <p className="max-w-3xl text-base leading-relaxed text-muted-foreground">{t.s4P1}</p>
        <PathDiagrams />
        <Card>
          <CardHeader>
            <CardTitle className="text-base">{t.pathChartTitle}</CardTitle>
          </CardHeader>
          <CardContent className="h-80">
            <ResponsiveContainer>
              <BarChart data={pathRows} margin={{ top: 8, right: 24, bottom: 8, left: 8 }}>
                <CartesianGrid strokeDasharray="3 3" opacity={0.3} />
                <XAxis dataKey="kind" interval={0} angle={-20} textAnchor="end" height={60} />
                <YAxis
                  scale="log"
                  domain={["auto", "auto"]}
                  width={70}
                  tickFormatter={(v) => formatCompact(Number(v))}
                />
                <Tooltip formatter={(v) => [formatCompact(Number(v)), t.fitChecks]} />
                <Bar dataKey="median" fill="#38bdf8" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      </section>

      <section className="space-y-3">
        <h2 className="text-2xl font-semibold tracking-tight">{t.s5Title}</h2>
        <p className="max-w-3xl text-base leading-relaxed text-muted-foreground">{t.s5P1}</p>
        <BinaryPlayground />
        <p className="max-w-3xl text-base leading-relaxed text-muted-foreground">{t.s5P2}</p>
      </section>

      <section className="max-w-3xl space-y-3">
        <h2 className="text-2xl font-semibold tracking-tight">{t.s6Title}</h2>
        <p className="text-base leading-relaxed text-muted-foreground">{t.s6P1}</p>
      </section>
    </div>
  );
}

export const meta = pageMeta("algorithms");
