import { pageMeta } from "@/seo";
// Algorithms, explained for high-schoolers, with real measurements from the
// site's own Rust engine (src/data/difficulty.json is generated by
// `cargo run --release --bin stats` in engine/).

import { LocalizedLink as Link } from "@/components/LocalizedLink";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Legend,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { DfsDemo } from "@/components/learn/DfsDemo";
import { TimeToSolve } from "@/components/learn/TimeToSolve";
import { PathDiagrams } from "@/components/learn/PathDiagrams";
import { BinaryPlayground } from "@/components/learn/BinaryPlayground";
import { useT } from "@/i18n";
import stats from "@/data/difficulty.json";
import { formatCompact } from "@/lib/format";
import { useIsClient } from "@/lib/utils";
import type { ReactElement } from "react";

// recharts measures its parent's layout; during the static prerender pass
// there is no layout and ResponsiveContainer warns about width/height -1.
// Render the chart only once mounted in the browser.
function ChartFrame({ children }: { children: ReactElement }) {
  const isClient = useIsClient();
  if (!isClient) return null;
  return (
    <ResponsiveContainer width="100%" height="100%" minWidth={0} minHeight={0}>
      {children}
    </ResponsiveContainer>
  );
}

interface DifficultyRow {
  size: number;
  colors: number;
  median: number;
  min: number;
  max: number;
  censored: number;
  seeds: number;
}

interface PathRow {
  kind: string;
  median: number;
  censored: number;
}

interface SpaceRow {
  size: number;
  log10Naive: number;
  log10Refined: number;
}

const difficulty = stats.difficulty as DifficultyRow[];
const pathRows = [...(stats.paths as PathRow[])].sort((a, b) => a.median - b.median);
const spaceRows = stats.searchSpace as SpaceRow[];

// One line per board size: median work vs number of colors. 3×3 is omitted —
// it solves near-instantly and just hugs the bottom axis without adding signal.
const SIZES = [...new Set(difficulty.map((d) => d.size))].filter((s) => s !== 3);
const colorsDomain = [...new Set(difficulty.map((d) => d.colors))].sort((a, b) => a - b);
const difficultyChart = colorsDomain.map((colors) => {
  const row: Record<string, number | null> = { colors };
  for (const s of SIZES) {
    const hit = difficulty.find((d) => d.size === s && d.colors === colors);
    row[`s${s}`] = hit ? hit.median : null;
  }
  return row;
});

const SIZE_COLORS: Record<number, string> = {
  3: "#94a3b8",
  4: "#38bdf8",
  5: "#34d399",
  6: "#fbbf24",
  7: "#fb923c",
  8: "#f87171",
};

const T = {
  en: {
    title: "How do you solve Eternity II with a computer?",
    intro: (
      <>
        No magic here, just three big ideas: <strong>trying things in order</strong>,{" "}
        <strong>undoing mistakes</strong>, and <strong>counting how bad it can get</strong>.
        Every number and chart on this page was measured by the same Rust engine that powers
        the <Link className="underline" to="/playground">playground</Link>, running on puzzles
        it generated itself.
      </>
    ),
    s1Title: "1 · Depth-first search: the maze strategy",
    s1P1: (
      <>
        Imagine exploring a maze: at every junction take the first corridor you haven't tried;
        when you hit a dead end, walk back to the last junction and take the next corridor.
        That's <strong>depth-first search (DFS)</strong>, and it's exactly how our solver
        plays Eternity II. The "junction" is an empty square; the "corridors" are every piece
        × rotation that still fits; the "walk back" is called <strong>backtracking</strong>.
      </>
    ),
    s1P2: (
      <>
        DFS is <em>complete</em>: given enough time it tries everything, so if a solution
        exists, it will be found. The catch is in the words "enough time". Here it is, slowed
        down to one decision per second:
      </>
    ),
    watchFullSpeed: "▶ Now watch it at full speed",
    s2Title: "2 · The exponential wall",
    s2P1: (
      <>
        How big is "everything"? For an n×n puzzle there are roughly n²! ways to order the
        pieces times 4 rotations each. The chart below shows the <em>number of digits</em> in
        that count. Notice it's a straight-ish line: every step up in size multiplies the work
        by an astronomical factor. The 16×16 box on your shelf sits at ≈560 digits.
      </>
    ),
    spaceChartTitle: "Digits in the search-space size, by board size",
    axisDigits: "digits",
    boardTooltip: (s: number | string) => `${s}×${s} board`,
    legendNaive: "all arrangements",
    legendRefined: "after corner/border deductions",
    s2P2: (
      <>
        The blue line is the first lesson in algorithm design: <strong>deductions shrink
        worlds</strong>. Just noticing that corner pieces must go in corners and border pieces
        on the rim removes ~100 digits. Real solvers stack many such deductions. And it's
        still not nearly enough.
      </>
    ),
    s2P3: <>"Digits" stay abstract, so let's make it personal:</>,
    zeroWallTitle: "How long is a 560-digit number? This long:",
    zeroWallCaption:
      "One followed by 559 zeros: 560 digits, exactly as many as the real count (about 9 × 10^559). Every single zero multiplies the count by ten.",
    s3Title: "3 · Measured difficulty: size and colors",
    s3Intro: (seeds: number | undefined) => (
      <>
        We generated hundreds of mini-puzzles and let the engine solve each one, counting{" "}
        <strong>nodes</strong> (candidate piece placements tested) until the first solution (median of {seeds}{" "}
        random puzzles per point; log scale!). Three things to see. Each extra row of board
        multiplies the work: the lines sit decades apart. <em>More</em> colors often make a
        puzzle <em>easier</em>, because wrong placements get rejected sooner instead of luring
        the search into deep dead ends. And every line shows something famous: a sharp{" "}
        <strong>hardness peak</strong>. Very few colors → tons of solutions, easy to stumble on
        one. Many colors → so constrained the search barely branches. The peak sits right in
        between — and, crucially, <strong>it slides to the right as the board grows</strong>: the
        6×6 line peaks at <strong>4 colors</strong>, the 8×8 line at <strong>6 colors</strong>,
        roughly one extra color per added row. At its peak the median 8×8 puzzle needs over{" "}
        <strong>2 billion</strong> piece placements, and most seeds there ran so long we had to
        stop measuring them (the flat tops are those censored points). One color either side and
        it collapses by a hundredfold. Extrapolate that one-color-per-row trend out to a 16×16
        board and the peak lands right around <strong>22 colors</strong> — exactly where
        Eternity II was built to sit. It isn't an accident past the peak; it's tuned to land
        <em> on</em> it.
      </>
    ),
    workChartTitle: "Work to solve (median nodes, log scale) vs number of colors",
    axisColors: "colors",
    fitChecks: "nodes",
    s4Title: "4 · The order you search in matters. A lot.",
    s4P1: (
      <>
        Same puzzles, same solver. The only change is the <em>order</em> in which squares get
        filled. Orders that keep new placements glued to already-placed neighbors (snake,
        spiral) constrain each step and prune early. Orders that scatter placements (random)
        leave pieces unconstrained and pay for it later. This is a real research topic, and
        you can <Link className="underline" to="/playground/paths">design your own order</Link>{" "}
        and race it. Here is what the classic orders actually look like; follow the arrows
        (red = first cell, green = last):
      </>
    ),
    pathChartTitle: "Median nodes on the same 6×6 puzzles, by fill order (log scale)",
    pathChartNote:
      "A subtlety worth naming (thanks to Dan Karlsson): row-major and column-major are the same order up to flipping the board across its diagonal, so over many puzzles they should cost the same — any gap between them here is sampling noise, not a real difference. The orders that genuinely differ are the ones with a different shape: a spiral, a diagonal, border-first.",
    pathChartDeeper: (
      <>
        The same question, taken all the way on the full 16×16 puzzle, is the{" "}
        <Link
          className="underline"
          to="/research/lab/experiments/raphael-anjou/dfs-study/findings"
        >
          DFS study
        </Link>
        : it measures what each fill order, heuristic and break rule buys, and finds the
        wrong order can cost more than 300 points of score.
      </>
    ),
    s5Title: "5 · Why computers think in binary here",
    s5P1: (
      <>
        A piece is just four small numbers (up, right, down, left motif). No pictures, no
        geometry. These four demos run live; watch them for a few seconds each:
      </>
    ),
    s5P2: (
      <>
        Stored as numbers, the entire official set is about 1&nbsp;KB. Serious solvers go
        further with <strong>bitsets</strong>: one 64-bit number carries a yes/no answer
        about 64 pieces at once, so a single CPU instruction filters 64 candidates
        simultaneously. That's how the fastest engines reach hundreds of millions of nodes
        per second. Representation, not just the algorithm, is part of the craft.
      </>
    ),
    s6Title: "6 · So how far does smart get you?",
    s6P1: (
      <>
        State-of-the-art attacks add constraint propagation (deduce forced placements before
        trying any), clever piece orderings, parallel search, and{" "}
        <Link className="underline" to="/research/lab/experiments/raphael-anjou/repair-study">
          local-repair heuristics
        </Link>{" "}
        that fix imperfect boards. They reach 469 and 470 of 480 matched edges. Extraordinary, and
        still short. The gap between "almost solved" and "solved" is where the open research
        lives: see the <Link className="underline" to="/research">Research</Link> section.
      </>
    ),
  },
  fr: {
    title: "Comment résoudre Eternity II avec un ordinateur ?",
    intro: (
      <>
        Aucune magie là-dedans, seulement trois grandes idées : <strong>essayer les
        possibilités une à une</strong>, <strong>revenir sur ses erreurs</strong> et{" "}
        <strong>mesurer jusqu'où la facture peut grimper</strong>. Tous les chiffres et tous les
        graphiques de cette page ont été produits par le moteur Rust qui anime l'
        <Link className="underline" to="/playground">aire de jeu</Link>, lancé sur des puzzles
        qu'il a lui-même générés.
      </>
    ),
    s1Title: "1 · La recherche en profondeur : la stratégie du labyrinthe",
    s1P1: (
      <>
        Imaginez que vous explorez un labyrinthe : à chaque carrefour, vous empruntez le
        premier couloir que vous n'avez pas encore tenté ; et dès que vous butez sur une
        impasse, vous retournez au dernier carrefour pour prendre le couloir d'à côté. Voilà la{" "}
        <strong>recherche en profondeur (DFS)</strong>, et c'est exactement comme cela que notre
        solveur s'attaque à Eternity II. Le « carrefour », c'est une case vide ; les
        « couloirs », ce sont toutes les pièces (et toutes leurs rotations) qui tiennent encore
        à cet endroit ; et le « demi-tour » porte un nom : le <strong>retour en arrière</strong>{" "}
        (backtracking).
      </>
    ),
    s1P2: (
      <>
        Le DFS est <em>complet</em> : laissez-lui assez de temps et il essaie tout, si bien
        qu'une solution existante finit toujours par tomber dans ses filets. Tout le piège tient
        dans ces quelques mots : « assez de temps ». Le voici, ralenti à une décision par
        seconde :
      </>
    ),
    watchFullSpeed: "▶ Voyez-le maintenant à pleine vitesse",
    s2Title: "2 · Le mur exponentiel",
    s2P1: (
      <>
        Ce « tout », au juste, c'est grand comment ? Pour un puzzle n×n, on compte à peu près
        n²! manières de ranger les pièces, multipliées par leurs 4 rotations. Le graphique
        ci-dessous indique le <em>nombre de chiffres</em> de ce total. Remarquez la ligne,
        presque droite : à chaque cran de taille, le travail est multiplié par un facteur
        astronomique. La boîte 16×16 posée sur votre étagère, elle, plafonne aux alentours de
        560 chiffres.
      </>
    ),
    spaceChartTitle: "Nombre de chiffres de l'espace de recherche, selon la taille du plateau",
    axisDigits: "chiffres",
    boardTooltip: (s: number | string) => `plateau ${s}×${s}`,
    legendNaive: "tous les arrangements",
    legendRefined: "après déductions coins/bords",
    s2P2: (
      <>
        La ligne bleue résume la toute première leçon de conception d'algorithmes : <strong>une
        déduction, c'est un monde qui rétrécit</strong>. Rien que de remarquer que les pièces de
        coin finissent dans les coins et les pièces de bord sur le pourtour, on raye déjà
        environ 100 chiffres. Les vrais solveurs enchaînent quantité de déductions du même
        genre. Et pourtant, on reste très loin du compte.
      </>
    ),
    s2P3: <>Le mot « chiffres » reste abstrait ; alors rendons la chose concrète :</>,
    zeroWallTitle: "À quoi ressemble un nombre de 560 chiffres ? À ceci :",
    zeroWallCaption:
      "Un 1 suivi de 559 zéros : 560 chiffres, soit exactement la taille du vrai total (environ 9 × 10^559). Et chaque zéro de plus multiplie ce total par dix.",
    s3Title: "3 · La difficulté, mesurée : taille et couleurs",
    s3Intro: (seeds: number | undefined) => (
      <>
        Nous avons généré des centaines de mini-puzzles et confié chacun au moteur, en comptant
        les <strong>nœuds</strong> (les placements de pièce mis à l'essai) jusqu'à la première
        solution (médiane sur {seeds} puzzles tirés au hasard pour chaque point ; échelle
        logarithmique !). Trois choses sautent aux yeux. D'abord, chaque rangée de plateau en
        plus multiplie le travail : les courbes sont espacées de plusieurs ordres de grandeur.
        Ensuite, <em>ajouter</em> des couleurs rend souvent le puzzle <em>plus facile</em>,
        parce qu'un mauvais placement se fait recaler plus vite au lieu d'attirer la recherche
        au fond d'une impasse. Enfin, chaque courbe trahit un phénomène bien connu : un{" "}
        <strong>pic de difficulté</strong>. Très peu de couleurs → des solutions à la pelle,
        faciles à dégoter par hasard. Beaucoup de couleurs → un puzzle si contraint que la
        recherche ne se ramifie presque plus. Le pic se loge entre les deux — et surtout,{" "}
        <strong>il glisse vers la droite à mesure que le plateau s'agrandit</strong> : la courbe
        6×6 culmine à <strong>4 couleurs</strong>, la courbe 8×8 à <strong>6 couleurs</strong>,
        soit grosso modo une couleur de plus par rangée ajoutée. À son sommet, le puzzle 8×8
        médian réclame plus de <strong>2 milliards</strong> de placements de pièces, et la
        plupart des graines ont tourné si longtemps qu'on a dû renoncer à les mesurer (les
        plateaux des courbes, ce sont ces points censurés). Une couleur de plus ou de moins, et
        tout s'effondre d'un facteur cent. Prolongez cette progression d'une couleur par rangée
        jusqu'au plateau 16×16 et le pic retombe pile sur les <strong>22 couleurs</strong> —
        exactement le réglage choisi pour Eternity II. Rien d'accidentel à ce qu'il se tienne
        au-delà du pic : il est calibré pour tomber <em>dessus</em>.
      </>
    ),
    workChartTitle:
      "Travail pour résoudre (médiane des nœuds, échelle log) selon le nombre de couleurs",
    axisColors: "couleurs",
    fitChecks: "nœuds",
    s4Title: "4 · L'ordre dans lequel on cherche compte. Et même énormément.",
    s4P1: (
      <>
        Mêmes puzzles, même solveur. La seule chose qui change, c'est le <em>parcours</em>,
        l'ordre dans lequel les cases se remplissent. Les parcours qui collent chaque nouveau
        placement à des voisins déjà posés (snake, spiral) verrouillent chaque étape et élaguent
        tôt. Ceux qui dispersent les placements (random) laissent les pièces libres de toute
        contrainte… et le paient cher plus loin. C'est un véritable sujet de recherche, et vous
        pouvez d'ailleurs <Link className="underline" to="/playground/paths">concevoir votre
        propre parcours</Link> pour le lancer dans la course. Voici l'allure réelle des
        parcours classiques ; suivez les flèches (rouge = première case, vert = dernière) :
      </>
    ),
    pathChartTitle:
      "Médiane des nœuds sur les mêmes puzzles 6×6, selon le parcours de remplissage (échelle log)",
    pathChartNote:
      "Une subtilité à nommer (merci à Dan Karlsson) : « rangées » et « colonnes » sont le même ordre à une symétrie diagonale près du plateau, donc sur de nombreux puzzles ils devraient coûter pareil — tout écart ici est du bruit d'échantillonnage, pas une vraie différence. Les ordres qui diffèrent vraiment sont ceux de forme différente : une spirale, une diagonale, le cadre d'abord.",
    pathChartDeeper: (
      <>
        La même question, poussée jusqu'au bout sur le vrai plateau 16×16, c'est l'
        <Link
          className="underline"
          to="/research/lab/experiments/raphael-anjou/dfs-study/findings"
        >
          étude DFS
        </Link>{" "}
        : elle mesure ce qu'apportent chaque ordre de remplissage, chaque heuristique et
        chaque règle de cassure, et montre que le mauvais ordre peut coûter plus de 300
        points de score.
      </>
    ),
    s5Title: "5 · Pourquoi, ici, les ordinateurs raisonnent en binaire",
    s5P1: (
      <>
        Une pièce, ce n'est rien d'autre que quatre petits nombres (les motifs du haut, de
        droite, du bas et de gauche). Ni image, ni géométrie. Les quatre démos ci-dessous
        tournent en direct ; accordez quelques secondes à chacune :
      </>
    ),
    s5P2: (
      <>
        Une fois codé sous forme de nombres, le jeu officiel au complet tient dans environ
        1&nbsp;Ko. Les solveurs sérieux poussent l'astuce plus loin avec les{" "}
        <strong>bitsets</strong> : un seul nombre de 64 bits transporte une réponse oui/non sur
        64 pièces à la fois, si bien qu'une unique instruction du processeur filtre 64
        candidates d'un seul coup. C'est ce qui permet aux moteurs les plus rapides d'abattre
        des centaines de millions de nœuds par seconde. La façon de représenter les données —
        pas seulement l'algorithme — fait partie du métier.
      </>
    ),
    s6Title: "6 · Alors, jusqu'où la finesse nous mène-t-elle ?",
    s6P1: (
      <>
        Les attaques de pointe ajoutent à tout cela la propagation de contraintes (déduire les
        placements forcés avant le moindre essai), des ordres de pièces malins, la recherche en
        parallèle et des{" "}
        <Link className="underline" to="/research/lab/experiments/raphael-anjou/repair-study">
          heuristiques de réparation locale
        </Link>{" "}
        qui rafistolent les plateaux
        imparfaits. Elles atteignent 469, voire 470 côtés appariés sur 480. C'est
        prodigieux — et toujours insuffisant. Cet écart entre « presque résolu » et « résolu »,
        c'est précisément là que se joue la recherche ouverte : rendez-vous dans la section{" "}
        <Link className="underline" to="/research">Recherche</Link>.
      </>
    ),
  },
  es: {
    title: "¿Cómo se resuelve Eternity II con un ordenador?",
    intro: (
      <>
        Aquí no hay magia, solo tres grandes ideas: <strong>probar posibilidades una a
        una</strong>, <strong>deshacer los errores</strong> y{" "}
        <strong>calcular hasta dónde puede dispararse el coste</strong>. Cada número y cada
        gráfico de esta página los midió el mismo motor Rust que impulsa el{" "}
        <Link className="underline" to="/playground">área de juego</Link>, ejecutándose sobre
        puzzles que él mismo generó.
      </>
    ),
    s1Title: "1 · Búsqueda en profundidad: la estrategia del laberinto",
    s1P1: (
      <>
        Imagina que exploras un laberinto: en cada cruce tomas el primer pasillo que aún no has
        probado; y en cuanto topas con un callejón sin salida, vuelves al último cruce y tomas
        el siguiente pasillo. Eso es la <strong>búsqueda en profundidad (DFS)</strong>, y es
        exactamente como nuestro solucionador ataca Eternity II. El «cruce» es una casilla
        vacía; los «pasillos» son cada pieza × rotación que todavía encaja; y a esa «vuelta
        atrás» se la llama <strong>backtracking</strong>.
      </>
    ),
    s1P2: (
      <>
        El DFS es <em>completo</em>: dale tiempo suficiente y lo prueba todo, así que si existe
        una solución, acabará encontrándola. La trampa está en esas palabras: «tiempo
        suficiente». Aquí lo tienes, ralentizado a una decisión por segundo:
      </>
    ),
    watchFullSpeed: "▶ Ahora míralo a toda velocidad",
    s2Title: "2 · El muro exponencial",
    s2P1: (
      <>
        Y ese «todo», ¿cómo de grande es? Para un puzzle n×n hay aproximadamente n²! formas de
        ordenar las piezas, multiplicadas por sus 4 rotaciones cada una. El gráfico de abajo
        muestra el <em>número de cifras</em> de esa cuenta. Fíjate en que es una línea casi
        recta: cada escalón de tamaño multiplica el trabajo por un factor astronómico. La caja
        16×16 que tienes en la estantería se sitúa en unas 560 cifras.
      </>
    ),
    spaceChartTitle: "Cifras del tamaño del espacio de búsqueda, según el tamaño del tablero",
    axisDigits: "cifras",
    boardTooltip: (s: number | string) => `tablero ${s}×${s}`,
    legendNaive: "todas las disposiciones",
    legendRefined: "tras deducciones de esquinas/bordes",
    s2P2: (
      <>
        La línea azul encierra la primera lección del diseño de algoritmos: <strong>una
        deducción encoge mundos</strong>. Con solo notar que las piezas de esquina van en las
        esquinas y las de borde en el perímetro, ya se tachan unas 100 cifras. Los
        solucionadores de verdad encadenan muchas deducciones así. Y aún no basta ni de lejos.
      </>
    ),
    s2P3: <>La palabra «cifras» sigue siendo abstracta, así que hagámoslo personal:</>,
    zeroWallTitle: "¿Cuánto ocupa un número de 560 cifras? Esto:",
    zeroWallCaption:
      "Un 1 seguido de 559 ceros: 560 cifras, exactamente tantas como la cuenta real (unos 9 × 10^559). Cada cero de más multiplica la cuenta por diez.",
    s3Title: "3 · La dificultad, medida: tamaño y colores",
    s3Intro: (seeds: number | undefined) => (
      <>
        Generamos cientos de mini-puzzles y dejamos que el motor resolviera cada uno, contando
        los <strong>nodos</strong> (los emplazamientos de pieza puestos a prueba) hasta la
        primera solución (mediana de {seeds} puzzles aleatorios por punto; ¡escala
        logarítmica!). Hay tres cosas que ver. Cada fila de más en el tablero multiplica el
        trabajo: las líneas se separan por varios órdenes de magnitud. <em>Añadir</em> colores
        suele hacer el puzzle <em>más fácil</em>, porque un emplazamiento erróneo se rechaza
        antes en lugar de arrastrar la búsqueda al fondo de un callejón sin salida. Y cada
        línea revela algo célebre: un marcado <strong>pico de dificultad</strong>. Muy pocos
        colores → soluciones a montones, fáciles de encontrar por azar. Muchos colores → un
        puzzle tan restringido que la búsqueda apenas se ramifica. El pico se aloja justo en
        medio y, sobre todo, <strong>se desplaza hacia la derecha a medida que crece el
        tablero</strong>: la línea 6×6 culmina en <strong>4 colores</strong>, la línea 8×8 en{" "}
        <strong>6 colores</strong>, más o menos un color más por cada fila añadida. En su pico,
        el puzzle 8×8 mediano exige más de <strong>2 mil millones</strong> de emplazamientos de
        piezas, y la mayoría de las semillas allí tardaron tanto que tuvimos que dejar de
        medirlas (las mesetas planas son esos puntos censurados). Un color a un lado u otro y
        todo se derrumba por un factor de cien. Prolonga esa tendencia de un color por fila
        hasta un tablero 16×16 y el pico cae justo en torno a los <strong>22 colores</strong>:
        exactamente donde se diseñó Eternity II para situarse. No es casualidad que quede más
        allá del pico; está calibrado para caer <em>sobre</em> él.
      </>
    ),
    workChartTitle:
      "Trabajo para resolver (mediana de nodos, escala log) según el número de colores",
    axisColors: "colores",
    fitChecks: "nodos",
    s4Title: "4 · El orden en que buscas importa. Y mucho.",
    s4P1: (
      <>
        Mismos puzzles, mismo solucionador. Lo único que cambia es el <em>orden</em> en que se
        rellenan las casillas. Los órdenes que mantienen cada nuevo emplazamiento pegado a
        vecinos ya colocados (snake, spiral) restringen cada paso y podan pronto. Los que
        dispersan los emplazamientos (random) dejan las piezas sin restricción y lo pagan más
        adelante. Es un tema de investigación de verdad, y puedes{" "}
        <Link className="underline" to="/playground/paths">diseñar tu propio orden</Link>{" "}
        y echarlo a correr. Este es el aspecto real de los órdenes clásicos; sigue las flechas
        (rojo = primera casilla, verde = última):
      </>
    ),
    pathChartTitle:
      "Mediana de nodos en los mismos puzzles 6×6, según el orden de relleno (escala log)",
    pathChartNote:
      "Una sutileza que conviene nombrar (gracias a Dan Karlsson): por filas y por columnas son el mismo orden salvo por voltear el tablero sobre su diagonal, así que en muchos puzzles deberían costar lo mismo; cualquier diferencia aquí es ruido de muestreo, no una diferencia real. Los órdenes que difieren de verdad son los de forma distinta: una espiral, una diagonal, el borde primero.",
    pathChartDeeper: (
      <>
        La misma pregunta, llevada hasta el final sobre el puzzle 16×16 completo, es el{" "}
        <Link
          className="underline"
          to="/research/lab/experiments/raphael-anjou/dfs-study/findings"
        >
          estudio DFS
        </Link>
        : mide lo que aporta cada orden de relleno, cada heurística y cada regla de ruptura, y
        descubre que el orden equivocado puede costar más de 300 puntos de puntuación.
      </>
    ),
    s5Title: "5 · Por qué aquí los ordenadores piensan en binario",
    s5P1: (
      <>
        Una pieza no es más que cuatro números pequeños (los motivos de arriba, derecha, abajo
        e izquierda). Ni imágenes, ni geometría. Estas cuatro demos funcionan en directo;
        obsérvalas unos segundos cada una:
      </>
    ),
    s5P2: (
      <>
        Guardado como números, el conjunto oficial entero ocupa alrededor de 1&nbsp;KB. Los
        solucionadores serios van más allá con los <strong>bitsets</strong>: un único número de
        64 bits transporta una respuesta sí/no sobre 64 piezas a la vez, de modo que una sola
        instrucción de la CPU filtra 64 candidatas de golpe. Así es como los motores más
        rápidos alcanzan cientos de millones de nodos por segundo. La representación, y no solo
        el algoritmo, forma parte del oficio.
      </>
    ),
    s6Title: "6 · Entonces, ¿hasta dónde te lleva la astucia?",
    s6P1: (
      <>
        Los ataques de vanguardia añaden propagación de restricciones (deducir los
        emplazamientos forzados antes de probar ninguno), ordenaciones de piezas ingeniosas,
        búsqueda en paralelo y{" "}
        <Link className="underline" to="/research/lab/experiments/raphael-anjou/repair-study">
          heurísticas de reparación local
        </Link>{" "}
        que arreglan tableros imperfectos. Alcanzan 469 y 470 de 480 aristas coincidentes.
        Extraordinario, y aún insuficiente. El hueco entre «casi resuelto» y «resuelto» es
        donde vive la investigación abierta: consulta la sección{" "}
        <Link className="underline" to="/research">Investigación</Link>.
      </>
    ),
  },
};

export default function Algorithms() {
  const t = useT(T);
  return (
    <div className="space-y-12">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">{t.title}</h1>
        <p className="mt-2 max-w-3xl text-muted-foreground">{t.intro}</p>
      </div>

      <section className="max-w-3xl space-y-3">
        <h2 className="text-2xl font-semibold tracking-tight">{t.s1Title}</h2>
        <p className="text-base leading-relaxed text-muted-foreground">{t.s1P1}</p>
        <p className="text-base leading-relaxed text-muted-foreground">{t.s1P2}</p>
        <DfsDemo />
        <Button variant="outline" size="sm" render={<Link to="/playground/watch" />}>
          {t.watchFullSpeed}
        </Button>
      </section>

      <section className="space-y-3">
        <h2 className="text-2xl font-semibold tracking-tight">{t.s2Title}</h2>
        <p className="max-w-3xl text-base leading-relaxed text-muted-foreground">{t.s2P1}</p>
        <Card>
          <CardHeader>
            <CardTitle className="text-base">{t.spaceChartTitle}</CardTitle>
          </CardHeader>
          <CardContent className="h-72">
            <ChartFrame>
              <LineChart data={spaceRows} margin={{ top: 8, right: 24, bottom: 8, left: 8 }}>
                <CartesianGrid strokeDasharray="3 3" opacity={0.3} />
                <XAxis dataKey="size" tickFormatter={(s) => `${s}×${s}`} />
                <YAxis width={60} label={{ value: t.axisDigits, angle: -90, position: "insideLeft" }} />
                <Tooltip
                  formatter={(v) => [`10^${Number(v).toFixed(0)}`, ""]}
                  labelFormatter={(s) => t.boardTooltip(String(s))}
                />
                <Legend />
                <Line name={t.legendNaive} dataKey="log10Naive" stroke="#f87171" dot={false} strokeWidth={2} />
                <Line name={t.legendRefined} dataKey="log10Refined" stroke="#38bdf8" dot={false} strokeWidth={2} />
              </LineChart>
            </ChartFrame>
          </CardContent>
        </Card>
        <p className="max-w-3xl text-base text-muted-foreground">{t.s2P2}</p>
        <div className="space-y-2">
          <p className="text-sm font-medium">{t.zeroWallTitle}</p>
          <div className="w-full rounded-lg border bg-muted/30 p-4 font-mono text-[11px] leading-relaxed break-all text-muted-foreground select-all">
            <span className="font-bold text-foreground">1</span>
            {"0".repeat(559)}
          </div>
          <p className="text-xs text-muted-foreground">{t.zeroWallCaption}</p>
        </div>
        <p className="max-w-3xl text-base text-muted-foreground">{t.s2P3}</p>
        <TimeToSolve />
      </section>

      <section className="space-y-3">
        <h2 className="text-2xl font-semibold tracking-tight">{t.s3Title}</h2>
        <p className="max-w-3xl text-base leading-relaxed text-muted-foreground">
          {t.s3Intro(difficulty[0]?.seeds)}
        </p>
        <Card>
          <CardHeader>
            <CardTitle className="text-base">{t.workChartTitle}</CardTitle>
          </CardHeader>
          <CardContent className="h-80">
            <ChartFrame>
              <LineChart data={difficultyChart} margin={{ top: 8, right: 24, bottom: 8, left: 8 }}>
                <CartesianGrid strokeDasharray="3 3" opacity={0.3} />
                <XAxis dataKey="colors" label={{ value: t.axisColors, position: "insideBottom", offset: -2 }} />
                <YAxis
                  scale="log"
                  domain={[10, 3e9]}
                  ticks={[100, 1e4, 1e6, 1e8, 1e9]}
                  interval={0}
                  allowDataOverflow
                  width={70}
                  tickFormatter={(v) => formatCompact(Number(v))}
                />
                <Tooltip formatter={(v) => [formatCompact(Number(v)), t.fitChecks]} />
                <Legend />
                {SIZES.map((s) => (
                  <Line
                    key={s}
                    name={`${s}×${s}`}
                    dataKey={`s${s}`}
                    stroke={SIZE_COLORS[s] ?? "#a78bfa"}
                    dot={false}
                    strokeWidth={2}
                    connectNulls
                  />
                ))}
              </LineChart>
            </ChartFrame>
          </CardContent>
        </Card>
      </section>

      <section className="space-y-3">
        <h2 className="text-2xl font-semibold tracking-tight">{t.s4Title}</h2>
        <p className="max-w-3xl text-base leading-relaxed text-muted-foreground">{t.s4P1}</p>
        <PathDiagrams />
        <Card>
          <CardHeader>
            <CardTitle className="text-base">{t.pathChartTitle}</CardTitle>
          </CardHeader>
          <CardContent className="h-80">
            <ChartFrame>
              <BarChart data={pathRows} margin={{ top: 8, right: 24, bottom: 8, left: 8 }}>
                <CartesianGrid strokeDasharray="3 3" opacity={0.3} />
                <XAxis dataKey="kind" interval={0} angle={-20} textAnchor="end" height={60} />
                <YAxis
                  scale="log"
                  domain={["auto", "auto"]}
                  width={70}
                  tickFormatter={(v) => formatCompact(Number(v))}
                />
                <Tooltip formatter={(v) => [formatCompact(Number(v)), t.fitChecks]} />
                <Bar dataKey="median" fill="#38bdf8" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ChartFrame>
          </CardContent>
        </Card>
        <p className="max-w-3xl text-sm text-muted-foreground">{t.pathChartNote}</p>
        <p className="max-w-3xl text-sm text-muted-foreground">{t.pathChartDeeper}</p>
      </section>

      <section className="space-y-3">
        <h2 className="text-2xl font-semibold tracking-tight">{t.s5Title}</h2>
        <p className="max-w-3xl text-base leading-relaxed text-muted-foreground">{t.s5P1}</p>
        <BinaryPlayground />
        <p className="max-w-3xl text-base leading-relaxed text-muted-foreground">{t.s5P2}</p>
      </section>

      <section className="max-w-3xl space-y-3">
        <h2 className="text-2xl font-semibold tracking-tight">{t.s6Title}</h2>
        <p className="text-base leading-relaxed text-muted-foreground">{t.s6P1}</p>
      </section>
    </div>
  );
}

export const meta = pageMeta("algorithms");
