// Auto-generated by-contribution hubs under
// /research/lab/experiments/by-contribution: an index listing the contribution
// kinds (with counts) and one hub per kind, each listing the pages that declare
// that contribution. Route-generated like the topic hubs (TopicPages.tsx): no
// MDX file backs them — they walk the manifest, filtering on doc.contribution.
//
// The `negative` hub is the celebrated dead-end shelf; it is surfaced with its
// own "What was ruled out" framing so a reader can browse the sound negatives
// as first-class results rather than footnotes.

import { useLang, useT } from "@/i18n";
import { LocalizedLink } from "@/components/LocalizedLink";
import { cn } from "@/lib/utils";
import { kindLabel, KIND_DOT } from "@/lib/research/nav";
import { researchDocs } from "@/lib/research/manifest";
import type { Lang } from "@/i18n";
import type { ContributionKind, ResearchDoc } from "@/lib/research/types";
import { DocsSidebar } from "./DocsSidebar";
import { ResearchSubnav } from "./ResearchSubnav";

export const BY_CONTRIBUTION_BASE = "/research/lab/experiments/by-contribution";

// The contribution axis, in the display order the methodology page uses (solver
// first, then everything else, with the negative shelf near the end).
export const CONTRIBUTION_ORDER: readonly ContributionKind[] = [
  "solver",
  "analysis",
  "reconstruction",
  "theory",
  "method",
  "measurement",
  "tool",
  "exposition",
  "negative",
];

const CONTRIBUTION_LABEL: Record<ContributionKind, Record<Lang, string>> = {
  solver: { en: "Solvers", fr: "Solveurs", es: "Solucionadores" },
  analysis: { en: "Analyses", fr: "Analyses", es: "Análisis" },
  reconstruction: { en: "Reconstructions", fr: "Reconstructions", es: "Reconstrucciones" },
  theory: { en: "Theory", fr: "Théorie", es: "Teoría" },
  method: { en: "Methods", fr: "Méthodes", es: "Métodos" },
  measurement: { en: "Measurements", fr: "Mesures", es: "Mediciones" },
  negative: { en: "What was ruled out", fr: "Ce qui a été écarté", es: "Lo que se descartó" },
  tool: { en: "Tools", fr: "Outils", es: "Herramientas" },
  exposition: { en: "Explainers", fr: "Exposés", es: "Explicaciones" },
};

// One line per kind: what this shelf collects. Reader-facing; translated.
const CONTRIBUTION_BLURB: Record<ContributionKind, Record<Lang, string>> = {
  solver: {
    en: "Runs that produce a competitive board by searching. Only these earn a row on the leaderboard.",
    fr: "Des runs qui produisent un plateau compétitif par recherche. Seuls ceux-là gagnent une ligne au classement.",
    es: "Runs que producen un tablero competitivo mediante búsqueda. Solo estos ganan una fila en la clasificación.",
  },
  analysis: {
    en: "Pages that prove or compute a property of an existing board or of the instance, without producing a new board.",
    fr: "Des pages qui démontrent ou calculent une propriété d'un plateau existant ou de l'instance, sans produire de nouveau plateau.",
    es: "Páginas que demuestran o calculan una propiedad de un tablero existente o de la instancia, sin producir un tablero nuevo.",
  },
  reconstruction: {
    en: "Decodes and rebuilds of the community's known work, to extract the insight behind a number that is theirs.",
    fr: "Des décodages et reconstitutions du travail connu de la communauté, pour en extraire l'enseignement derrière un nombre qui est le leur.",
    es: "Decodificaciones y reconstrucciones del trabajo conocido de la comunidad, para extraer la idea tras un número que es suyo.",
  },
  theory: {
    en: "Mathematical properties, laws, and impossibility proofs about the puzzle.",
    fr: "Des propriétés mathématiques, des lois et des preuves d'impossibilité sur le casse-tête.",
    es: "Propiedades matemáticas, leyes y pruebas de imposibilidad sobre el rompecabezas.",
  },
  method: {
    en: "Techniques described for reuse, rather than a single scored run.",
    fr: "Des techniques décrites pour être réutilisées, plutôt qu'un unique run scoré.",
    es: "Técnicas descritas para su reutilización, en lugar de una única ejecución con puntuación.",
  },
  measurement: {
    en: "Benchmarks and empirical observations about solvers or instances.",
    fr: "Des benchmarks et des observations empiriques sur les solveurs ou les instances.",
    es: "Benchmarks y observaciones empíricas sobre solucionadores o instancias.",
  },
  negative: {
    en: "Sound dead ends, kept as first-class results: an idea run with rigour that did not pay off, and what its ceiling turned out to be.",
    fr: "Des impasses solides, gardées comme résultats à part entière : une idée menée avec rigueur qui n'a pas payé, et ce qu'a été son plafond.",
    es: "Callejones sin salida sólidos, guardados como resultados de pleno derecho: una idea llevada con rigor que no dio fruto, y cuál resultó ser su techo.",
  },
  tool: {
    en: "Software artifacts: engines, viewers, and checkers.",
    fr: "Des artefacts logiciels : moteurs, visionneuses et vérificateurs.",
    es: "Artefactos de software: motores, visores y verificadores.",
  },
  exposition: {
    en: "Explainers written for a reader, not a scored run.",
    fr: "Des exposés écrits pour un lecteur, non un run scoré.",
    es: "Explicaciones escritas para un lector, no un run con puntuación.",
  },
};

const T = {
  en: {
    research: "Research",
    lab: "The lab",
    experiments: "Experiments",
    index: "By contribution",
    indexLede:
      "The wiki sliced by what kind of result each page is, not where it lives: the solvers that score, the analyses and theory, the measurements and tools, and the dead ends kept as first-class negatives. Pick a shelf to browse it.",
    pages: (n: number) => (n === 1 ? "1 page" : `${n} pages`),
    empty: "Nothing carries this contribution yet.",
    negativeCallout: "Browse what was ruled out",
    negativeCalloutBody:
      "The sound dead ends are a shelf of their own: ideas run with rigour that did not pay off, kept as results rather than hidden.",
  },
  fr: {
    research: "Recherche",
    lab: "Le laboratoire",
    experiments: "Expériences",
    index: "Par contribution",
    indexLede:
      "Le wiki découpé selon le type de résultat de chaque page, non selon l'endroit où elle réside : les solveurs qui scorent, les analyses et la théorie, les mesures et les outils, et les impasses gardées comme résultats négatifs à part entière. Choisissez une étagère pour la parcourir.",
    pages: (n: number) => (n === 1 ? "1 page" : `${n} pages`),
    empty: "Rien ne porte encore cette contribution.",
    negativeCallout: "Parcourir ce qui a été écarté",
    negativeCalloutBody:
      "Les impasses solides forment leur propre étagère : des idées menées avec rigueur qui n'ont pas payé, gardées comme résultats plutôt que dissimulées.",
  },
  es: {
    research: "Investigación",
    lab: "El laboratorio",
    experiments: "Experimentos",
    index: "Por contribución",
    indexLede:
      "El wiki organizado según qué tipo de resultado es cada página, no según dónde reside: los solucionadores que puntúan, los análisis y la teoría, las mediciones y las herramientas, y los callejones sin salida guardados como resultados negativos de pleno derecho. Elige un estante para explorarlo.",
    pages: (n: number) => (n === 1 ? "1 página" : `${n} páginas`),
    empty: "Nada lleva todavía esta contribución.",
    negativeCallout: "Explorar lo que se descartó",
    negativeCalloutBody:
      "Los callejones sin salida sólidos forman su propio estante: ideas llevadas con rigor que no dieron fruto, guardadas como resultados en lugar de ocultarse.",
  },
};

function labelOf(kind: ContributionKind, lang: Lang): string {
  return CONTRIBUTION_LABEL[kind][lang] ?? CONTRIBUTION_LABEL[kind].en;
}
function blurbOf(kind: ContributionKind, lang: Lang): string {
  return CONTRIBUTION_BLURB[kind][lang] ?? CONTRIBUTION_BLURB[kind].en;
}

/** Title + description for a contribution hub, for the route's <meta> tags. */
export function contributionMeta(
  kind: ContributionKind,
  lang: Lang,
): { title: string; description: string } {
  return { title: labelOf(kind, lang), description: blurbOf(kind, lang) };
}

/** Pages that declare a given contribution, in reading order. */
function membersOf(lang: Lang, kind: ContributionKind): ResearchDoc[] {
  return researchDocs(lang).filter((d) => d.contribution === kind);
}

function Frame({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <ResearchSubnav />
      <div className="lg:grid lg:grid-cols-[15rem_minmax(0,1fr)] lg:gap-10">
        <DocsSidebar section={null} />
        <div className="min-w-0">{children}</div>
      </div>
    </div>
  );
}

function Crumbs({ current }: { current?: string }) {
  const t = useT(T);
  return (
    <nav className="flex flex-wrap items-center gap-1.5 text-sm text-muted-foreground">
      <LocalizedLink to="/research" className="hover:text-foreground">
        {t.research}
      </LocalizedLink>
      <span aria-hidden>/</span>
      <LocalizedLink to="/research/lab/experiments" className="hover:text-foreground">
        {t.experiments}
      </LocalizedLink>
      <span aria-hidden>/</span>
      {current ? (
        <>
          <LocalizedLink to={BY_CONTRIBUTION_BASE} className="hover:text-foreground">
            {t.index}
          </LocalizedLink>
          <span aria-hidden>/</span>
          <span className="text-foreground">{current}</span>
        </>
      ) : (
        <span className="text-foreground">{t.index}</span>
      )}
    </nav>
  );
}

function PageCard({ doc }: { doc: ResearchDoc }) {
  const { lang } = useLang();
  return (
    <LocalizedLink
      to={doc.url}
      className="group block rounded-lg border p-4 transition-shadow hover:shadow-md"
    >
      <div className="flex items-center gap-2">
        <span className={cn("h-2 w-2 shrink-0 rounded-full", KIND_DOT[doc.kind])} aria-hidden />
        <span className="text-[10px] font-medium uppercase tracking-wide text-muted-foreground">
          {kindLabel(doc.kind, lang)}
        </span>
      </div>
      <div className="mt-1.5 text-sm font-semibold tracking-tight group-hover:underline">
        {doc.title}
      </div>
      <p className="mt-1 text-xs leading-snug text-muted-foreground">{doc.description}</p>
    </LocalizedLink>
  );
}

export function ContributionIndex() {
  const t = useT(T);
  const { lang } = useLang();
  const counts = new Map<ContributionKind, number>();
  for (const k of CONTRIBUTION_ORDER) counts.set(k, membersOf(lang, k).length);
  const present = CONTRIBUTION_ORDER.filter((k) => (counts.get(k) ?? 0) > 0);
  const negativeCount = counts.get("negative") ?? 0;

  return (
    <Frame>
      <Crumbs />
      <header className="mt-4 space-y-3">
        <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">{t.index}</h1>
        <p className="text-lg text-muted-foreground">{t.indexLede}</p>
      </header>

      {negativeCount > 0 && (
        <LocalizedLink
          to={`${BY_CONTRIBUTION_BASE}/negative`}
          className="group mt-6 block rounded-lg border border-rose-500/30 bg-rose-500/5 p-4 transition-shadow hover:shadow-md"
        >
          <div className="flex items-baseline justify-between gap-2">
            <span className="text-sm font-semibold tracking-tight text-rose-700 group-hover:underline dark:text-rose-300">
              {t.negativeCallout}
            </span>
            <span className="text-xs tabular-nums text-muted-foreground">
              {t.pages(negativeCount)}
            </span>
          </div>
          <p className="mt-1.5 text-xs leading-relaxed text-muted-foreground">
            {t.negativeCalloutBody}
          </p>
        </LocalizedLink>
      )}

      <div className="mt-8 grid gap-3 sm:grid-cols-2">
        {present.map((k) => (
          <LocalizedLink
            key={k}
            to={`${BY_CONTRIBUTION_BASE}/${k}`}
            className="group block rounded-lg border p-4 transition-shadow hover:shadow-md"
          >
            <div className="flex items-baseline justify-between gap-2">
              <span className="text-sm font-semibold tracking-tight group-hover:underline">
                {labelOf(k, lang)}
              </span>
              <span className="text-xs tabular-nums text-muted-foreground">
                {t.pages(counts.get(k) ?? 0)}
              </span>
            </div>
            <p className="mt-1.5 text-xs leading-relaxed text-muted-foreground">{blurbOf(k, lang)}</p>
          </LocalizedLink>
        ))}
      </div>
    </Frame>
  );
}

export function ContributionHub({ kind }: { kind: ContributionKind }) {
  const t = useT(T);
  const { lang } = useLang();
  const members = membersOf(lang, kind);
  return (
    <Frame>
      <Crumbs current={labelOf(kind, lang)} />
      <header className="mt-4 space-y-3">
        <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">{labelOf(kind, lang)}</h1>
        <p className="text-lg text-muted-foreground">{blurbOf(kind, lang)}</p>
      </header>
      {members.length === 0 ? (
        <p className="mt-8 rounded-lg border border-dashed p-6 text-sm text-muted-foreground">
          {t.empty}
        </p>
      ) : (
        <>
          <p className="mt-6 text-sm text-muted-foreground">{t.pages(members.length)}</p>
          <div className="mt-3 grid gap-3 sm:grid-cols-2">
            {members.map((d) => (
              <PageCard key={d.url} doc={d} />
            ))}
          </div>
        </>
      )}
    </Frame>
  );
}

/** by-contribution index URL, or a hub's ContributionKind, or null if not one
 *  of these routes. Returns "" for the index. */
export function contributionRouteFor(path: string): "" | ContributionKind | null {
  if (path === BY_CONTRIBUTION_BASE) return "";
  const m = new RegExp(`^${BY_CONTRIBUTION_BASE}/([a-z-]+)$`).exec(path);
  const slug = m?.[1];
  if (!slug) return null;
  return (CONTRIBUTION_ORDER as readonly string[]).includes(slug)
    ? (slug as ContributionKind)
    : null;
}
