// Auto-generated by-contribution hubs under
// /research/lab/experiments/by-contribution: an index listing the contribution
// kinds (with counts) and one hub per kind, each listing the pages that declare
// that contribution. Route-generated like the topic hubs (TopicPages.tsx): no
// MDX file backs them — they walk the manifest, filtering on doc.contribution.
//
// The `negative` hub is the celebrated dead-end shelf; it is surfaced with its
// own "What was ruled out" framing so a reader can browse the sound negatives
// as first-class results rather than footnotes.

import { useLang, useT } from "@/i18n";
import { LocalizedLink } from "@/components/LocalizedLink";
import { cn } from "@/lib/utils";
import { kindLabel, KIND_DOT } from "@/lib/research/nav";
import {
  BY_CONTRIBUTION_BASE,
  CONTRIBUTION_ORDER,
  contributionBlurb,
  contributionLabel,
  contributionMembers,
} from "@/lib/research/contribution";
import type { ContributionKind, ResearchDoc } from "@/lib/research/types";
import { DocsSidebar } from "./DocsSidebar";
import { ResearchSubnav } from "./ResearchSubnav";

const T = {
  en: {
    research: "Research",
    lab: "The lab",
    experiments: "Experiments",
    index: "By contribution",
    indexLede:
      "The wiki sliced by what kind of result each page is, not where it lives: the solvers that score, the analyses and theory, the measurements and tools, and the dead ends kept as first-class negatives. Pick a shelf to browse it.",
    pages: (n: number) => (n === 1 ? "1 page" : `${n} pages`),
    empty: "Nothing carries this contribution yet.",
    negativeCallout: "Browse what was ruled out",
    negativeCalloutBody:
      "The sound dead ends are a shelf of their own: ideas run with rigour that did not pay off, kept as results rather than hidden.",
  },
  fr: {
    research: "Recherche",
    lab: "Le laboratoire",
    experiments: "Expériences",
    index: "Par contribution",
    indexLede:
      "Le wiki découpé selon le type de résultat de chaque page, non selon l'endroit où elle réside : les solveurs qui scorent, les analyses et la théorie, les mesures et les outils, et les impasses gardées comme résultats négatifs à part entière. Choisissez une étagère pour la parcourir.",
    pages: (n: number) => (n === 1 ? "1 page" : `${n} pages`),
    empty: "Rien ne porte encore cette contribution.",
    negativeCallout: "Parcourir ce qui a été écarté",
    negativeCalloutBody:
      "Les impasses solides forment leur propre étagère : des idées menées avec rigueur qui n'ont pas payé, gardées comme résultats plutôt que dissimulées.",
  },
  es: {
    research: "Investigación",
    lab: "El laboratorio",
    experiments: "Experimentos",
    index: "Por contribución",
    indexLede:
      "El wiki organizado según qué tipo de resultado es cada página, no según dónde reside: los solucionadores que puntúan, los análisis y la teoría, las mediciones y las herramientas, y los callejones sin salida guardados como resultados negativos de pleno derecho. Elige un estante para explorarlo.",
    pages: (n: number) => (n === 1 ? "1 página" : `${n} páginas`),
    empty: "Nada lleva todavía esta contribución.",
    negativeCallout: "Explorar lo que se descartó",
    negativeCalloutBody:
      "Los callejones sin salida sólidos forman su propio estante: ideas llevadas con rigor que no dieron fruto, guardadas como resultados en lugar de ocultarse.",
  },
};

function Frame({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <ResearchSubnav />
      <div className="lg:grid lg:grid-cols-[15rem_minmax(0,1fr)] lg:gap-10">
        <DocsSidebar section={null} />
        <div className="min-w-0">{children}</div>
      </div>
    </div>
  );
}

function Crumbs({ current }: { current?: string }) {
  const t = useT(T);
  return (
    <nav className="flex flex-wrap items-center gap-1.5 text-sm text-muted-foreground">
      <LocalizedLink to="/research" className="hover:text-foreground">
        {t.research}
      </LocalizedLink>
      <span aria-hidden>/</span>
      <LocalizedLink to="/research/lab/experiments" className="hover:text-foreground">
        {t.experiments}
      </LocalizedLink>
      <span aria-hidden>/</span>
      {current ? (
        <>
          <LocalizedLink to={BY_CONTRIBUTION_BASE} className="hover:text-foreground">
            {t.index}
          </LocalizedLink>
          <span aria-hidden>/</span>
          <span className="text-foreground">{current}</span>
        </>
      ) : (
        <span className="text-foreground">{t.index}</span>
      )}
    </nav>
  );
}

function PageCard({ doc }: { doc: ResearchDoc }) {
  const { lang } = useLang();
  return (
    <LocalizedLink
      to={doc.url}
      className="group block rounded-lg border p-4 transition-shadow hover:shadow-md"
    >
      <div className="flex items-center gap-2">
        <span className={cn("h-2 w-2 shrink-0 rounded-full", KIND_DOT[doc.kind])} aria-hidden />
        <span className="text-[10px] font-medium uppercase tracking-wide text-muted-foreground">
          {kindLabel(doc.kind, lang)}
        </span>
      </div>
      <div className="mt-1.5 text-sm font-semibold tracking-tight group-hover:underline">
        {doc.title}
      </div>
      <p className="mt-1 text-xs leading-snug text-muted-foreground">{doc.description}</p>
    </LocalizedLink>
  );
}

export function ContributionIndex() {
  const t = useT(T);
  const { lang } = useLang();
  const counts = new Map<ContributionKind, number>();
  for (const k of CONTRIBUTION_ORDER) counts.set(k, contributionMembers(lang, k).length);
  const present = CONTRIBUTION_ORDER.filter((k) => (counts.get(k) ?? 0) > 0);
  const negativeCount = counts.get("negative") ?? 0;

  return (
    <Frame>
      <Crumbs />
      <header className="mt-4 space-y-3">
        <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">{t.index}</h1>
        <p className="text-lg text-muted-foreground">{t.indexLede}</p>
      </header>

      {negativeCount > 0 && (
        <LocalizedLink
          to={`${BY_CONTRIBUTION_BASE}/negative`}
          className="group mt-6 block rounded-lg border border-rose-500/30 bg-rose-500/5 p-4 transition-shadow hover:shadow-md"
        >
          <div className="flex items-baseline justify-between gap-2">
            <span className="text-sm font-semibold tracking-tight text-rose-700 group-hover:underline dark:text-rose-300">
              {t.negativeCallout}
            </span>
            <span className="text-xs tabular-nums text-muted-foreground">
              {t.pages(negativeCount)}
            </span>
          </div>
          <p className="mt-1.5 text-xs leading-relaxed text-muted-foreground">
            {t.negativeCalloutBody}
          </p>
        </LocalizedLink>
      )}

      <div className="mt-8 grid gap-3 sm:grid-cols-2">
        {present.map((k) => (
          <LocalizedLink
            key={k}
            to={`${BY_CONTRIBUTION_BASE}/${k}`}
            className="group block rounded-lg border p-4 transition-shadow hover:shadow-md"
          >
            <div className="flex items-baseline justify-between gap-2">
              <span className="text-sm font-semibold tracking-tight group-hover:underline">
                {contributionLabel(k, lang)}
              </span>
              <span className="text-xs tabular-nums text-muted-foreground">
                {t.pages(counts.get(k) ?? 0)}
              </span>
            </div>
            <p className="mt-1.5 text-xs leading-relaxed text-muted-foreground">{contributionBlurb(k, lang)}</p>
          </LocalizedLink>
        ))}
      </div>
    </Frame>
  );
}

export function ContributionHub({ kind }: { kind: ContributionKind }) {
  const t = useT(T);
  const { lang } = useLang();
  const members = contributionMembers(lang, kind);
  return (
    <Frame>
      <Crumbs current={contributionLabel(kind, lang)} />
      <header className="mt-4 space-y-3">
        <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">{contributionLabel(kind, lang)}</h1>
        <p className="text-lg text-muted-foreground">{contributionBlurb(kind, lang)}</p>
      </header>
      {members.length === 0 ? (
        <p className="mt-8 rounded-lg border border-dashed p-6 text-sm text-muted-foreground">
          {t.empty}
        </p>
      ) : (
        <>
          <p className="mt-6 text-sm text-muted-foreground">{t.pages(members.length)}</p>
          <div className="mt-3 grid gap-3 sm:grid-cols-2">
            {members.map((d) => (
              <PageCard key={d.url} doc={d} />
            ))}
          </div>
        </>
      )}
    </Frame>
  );
}
